"""change_photo_url_to_avatar

Revision ID: 0003
Revises: 0002
Create Date: 2024-08-22 00:00:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old photo_url column and add new avatar column
    op.drop_column("profiles", "photo_url")
    op.add_column("profiles", sa.Column("avatar", sa.String(), nullable=True))
    op.create_foreign_key("fk_profiles_avatar_files_id", "profiles", "files", ["avatar"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_profiles_avatar_files_id", "profiles", type_="foreignkey")
    op.drop_column("profiles", "avatar")
    op.add_column("profiles", sa.Column("photo_url", sa.String(), nullable=True))
    # ### end Alembic commands ###
