"""create_friends_and_invitations_tables

Revision ID: 0004
Revises: 0003
Create Date: 2024-08-22 00:00:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create friends table
    op.create_table(
        "friends",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_1", sa.String(), nullable=False),
        sa.Column("user_2", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_1"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_2"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_1", "user_2", name="uq_friends_users"),
    )
    op.create_index(op.f("ix_friends_id"), "friends", ["id"], unique=False)

    # Create invitations table
    op.create_table(
        "invitations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_invitations_user"),
    )
    op.create_index(op.f("ix_invitations_id"), "invitations", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invitations_id"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_friends_id"), table_name="friends")
    op.drop_table("friends")
    # ### end Alembic commands ###
